### ISSUE TITLE
Invalid address 0x0

### ISSUE THREAD

**Issue by aissat** [hteso/iaito#175]
**radare2**:
`radare2 1.4.0 0 @ linux-x86-64 git.1.4.0
commit: HEAD build: 2017-05-02__20:39:14`

**Os**:
`Linux archost 4.10.16-1-ck-haswell `

**run**:

```
FILE OPEN (ls)
BITS 64
[Invalid address 0x0. Try with io.va=trueand entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
Oops at 0x00000000 (ff ff ff ...)
Unknown opcode
Cannot find function in 0x00000000
Oops at 0x00000000 (ff ff ff ...)
qcore->getFunctionRefs: No function found
qcore->getCycloComplex: no fcn foundNo functions to diff
debug output: Graph Offset: ''
qcore->getFunctionRefs: No function found
qcore->getCycloComplex: no fcn foundFailed to parse JSON: illegal value
qcore->getFunctionRefs: No function found
qcore->getCycloComplex: no fcn foundNo project
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/

```

**Comment by dashnine** [comment]
Not sure if this is related, but it appears to be similar: I get a crash on the XREF functionality.

To replicate:
Open Binary: Jump Outdated Elephants, from Google's 2016 CTF - [link_to_ELF_via_ctftime](https://storage.googleapis.com/ctf-teasers/154817c0b652025ff4590759439810ebd4a658bd190508ac22aaf8f414766468)

Click Functions
Click (or double-click) fcn.08048630
Right click and choose X-refs
Click the "X-Refs to:" item (`80486af       call fcn.08048630`)
Note the code preview is empty
Double-click to crash.

Crashes at xrefsdialog.cpp@88 due to fcn being null. Note: there is valid assembly at 0x80486af:
```
call fcn.08048630
0x080486b4           mov byte section_end.LOAD1, 1                    ; [0x804a03c:1]=71 ; "GCC: (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4"
0x080486bb           leave
0x080486bc           ret
```

**Comment by trufae** [comment]
just paste backtrace and the null deref will be obvious

**Comment by trufae** [comment]
also, update to r2-1.5

**Comment by dashnine** [comment]
Full Backtrace (and a simpler stack trace) should be attached.  For reference, See Thread 1:

```
`#0  0x00000000004c0262 in XrefsDialog::on_toTreeWidget_itemDoubleClicked (this=0x6fa4da0, item=0x74f1b10, column=1) at ../src/dialogs/xrefsdialog.cpp:88
        offset = {static null = {<No data fields>}, d = 0x737ea90}
        fcn = 0x0`
```

[Null_deref_backtrace.txt](https://github.com/hteso/iaito/files/1039862/Null_deref_backtrace.txt)
[simple_stacktrace.txt](https://github.com/hteso/iaito/files/1039866/simple_stacktrace.txt)
