### ISSUE TITLE
Desktop file on GNU/Linux

### ISSUE THREAD

**Issue by noirecat** [hteso/iaito#195]
How to create .desktop file iaito and display on menu.

**Comment by NieDzejkob** [comment]
Copy a different desktop file and change it. It's a text file.

**Comment by ballessay** [comment]
Well there is such file in source https://github.com/hteso/iaito/blob/master/src/iaito.desktop. But currently only used for the AppImage build. I guess you would need to change the Icon and Exec entries with paths to the correct files (note: iaito.png is currently just a copy of https://github.com/hteso/iaito/blob/master/src/img/logo-small.png)

**Comment by xarkes** [comment]
Ping, can anyone handle this?

**Comment by wobbol** [comment]
I can.

**Comment by wobbol** [comment]
Actually, this is already taken care of if you use:
```sh
mkdir build
cd build
qmake ../src
make install_share_applications
```
install_share_application is defined at line 1723
There is a lot here that I don't understand about when this makefile line would get run, but this will get a desktop entry in the right place for a menu item to appear.
Since this Makefile is generated with qmake I have no idea how I can get an effective ` install -m644 iaito/src/img/logo-small.png /usr/local/share/pixmaps/iaito.png` put in here.

**Comment by xarkes** [comment]
Maybe the travis file can help? https://github.com/hteso/iaito/blob/master/.travis.yml

**Comment by wobbol** [comment]
that file gives me a good overview of what is happening. I guess the file
to add this in is CMakeLists.txt then. I am struggling to get a hand hold
there. I'll come back with some questions after lunch.
